apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-postgres-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth-postgres
    template:
        metadata:
            labels:
                app: auth-postgres
        spec:
            containers:
                - name: auth-postgres
                  image: postgres:13-alpine
                  ports:
                    - containerPort: 5432
                  env:
                    - name: POSTGRES_DB
                      value: security_app
                    - name: POSTGRES_USER
                      value: admin
                    - name: POSTGRES_PASSWORD
                      value: password
---
apiVersion: v1
kind: Service
metadata:
    name: auth-postgres-srv
spec:
    selector:
        app: auth-postgres
    ports:
        - name: db
          protocol: TCP
          port: 5432
          targetPort: 5432