apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: g8h9/auth
                  env:
                    - name: POSTGRES_USER
                      value: 'admin'
                    - name: POSTGRES_PASSWORD
                      value: 'password'
                    - name: POSTGRES_URI
                      value: 'jdbc:postgresql://auth-postgres-srv:5432/security_app'
                    - name: JWT_KEY
                      value: 'a749fj623jd6'
---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 9000
          targetPort: 9000